sudo: required
services:
  - docker
before_install:
  - docker build -t duypham9895/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true duypham9895/docker-react yarn test --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucker_name: "elasticbeanstalk-us-east-1-115547051552"
  bucket_path: "docker-react"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
